Api - Reference Data Type Id
estagio-2023/realestate-api pull request #36
Opened 2024-04-19 15:51 UTC by RafaelMeha

Created get method for reference data by type and id

2024-04-19 16:34 UTC, Silva096 commented on RealestateApi/Controllers/ReferenceDataController.cs
> +        public async Task<ReferenceDataModel> GetReferenceDataAsync(string refDataType, int refDataId)
Change name from "GetReferenceDataAsync" to "GetReferenceDataByIdAsync" please

2024-04-19 16:35 UTC, Silva096 commented on RealestateApi/Repository/ReferenceDataRepository.cs
> +            return null;
You should not return null, you should return response.

By returning response inside a while loop, you will return as soon as the first one is read.

2024-04-22 08:26 UTC, Silva096 requested changes
Comments

2024-04-23 07:55 UTC, jonathan-osorio approved these changes

2024-04-23 07:55 UTC, jonathan-osorio commented on RealestateApi/Repository/ReferenceDataRepository.cs
> +
extra line not needed

2024-04-23 07:58 UTC, RafaelMeha commented on RealestateApi/Repository/ReferenceDataRepository.cs
> +
thanks :)

2024-04-23 08:33 UTC, Silva096 approved these changes

2024-04-23 08:36 UTC, merged