API - Post RealEstate Validations
estagio-2023/realestate-api pull request #66
Opened 2024-05-02 16:41 UTC by diogo-s4ntos

Added validations to method POST of RealEstate.

2024-05-03 13:39 UTC, jonathan-osorio requested changes
The validations are returning more than one message to the same rule: Ex.:
  "Price": [
      "'Price' deve ser definido.",
      "A valid price is required."
    ]
    
    Also there is no cascading on the rules. Maybe we should add it as validator oprions in the Program.cs so the rules don't overlap in the same fields, for exemple the not null and the lenght rules.

2024-05-15 15:42 UTC, Silva096 commented on RealestateApi/Controllers/RealEstateController.cs
> +            if (!validationResult.IsValid)
I suspect that if you remove this If statement, and line 58, the validator will be triggered automatically.
Can you give it a try and let me know please?

2024-05-15 15:53 UTC, Silva096 commented on RealestateApi/Validators/AddRealEstateValidator.cs
> +        public bool ExistInRefData(string refDataType, int refDataId)
This can be changed to private instead of public

2024-05-16 14:16 UTC, pmzpro requested changes
There's an error if you insert an inexisting id for customerId and agentId:

The api return the error 500 but should return the error 400 instead.

2024-05-16 15:27 UTC, pmzpro approved these changes

2024-05-16 15:39 UTC, Silva096 commented on RealestateApi/Controllers/RealEstateController.cs
> +        public RealEstateController(ILogger<RealEstateController> logger, IRealEstateService realEstateService, IValidator<AddRealEstateRequestDto> realEstateRequestValidatorDto)
remove validator from constructor.

2024-05-16 16:19 UTC, Silva096 approved these changes

2024-05-16 16:20 UTC, merged